name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: 'Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'Bug Fixes'
    labels:
      - 'bug'
      - 'fix'
  - title: 'Security Hardening'
    labels:
      - 'security'
      - 'hardening'

change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
no-changes-template: '- No user-facing changes.'

template: |
  ## Changes
  $CHANGES

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'patch'
      - 'bug'
      - 'fix'
      - 'security'
      - 'hardening'
  default: patch
