#!/bin/bash
set -euo pipefail

ROOT=$(cd "$(dirname "$0")/../.." && pwd)
HELPER="$ROOT/package/nginx-telego/files/usr/libexec/nginx-telego-files"
work=$(mktemp -d)
trap 'rm -rf -- "$work"' EXIT

rootfs="$work/rootfs"
mkdir -p \
  "$rootfs/etc/nginx/conf.d" \
  "$rootfs/etc/nginx/snippets" \
  "$rootfs/usr/share/nginx-telego/templates"

cp "$ROOT/package/nginx-telego/files/conf.d/telego.conf" \
  "$rootfs/usr/share/nginx-telego/templates/telego.conf"
cp "$ROOT/package/nginx-telego/files/telego.locations" \
  "$rootfs/usr/share/nginx-telego/templates/telego.locations"
cp "$ROOT/package/nginx-telego/files/usr/share/nginx-telego/ownership.tsv" \
  "$rootfs/usr/share/nginx-telego/ownership.tsv"

cp "$rootfs/usr/share/nginx-telego/templates/telego.conf" \
  "$rootfs/etc/nginx/conf.d/telego.conf"
cp "$rootfs/usr/share/nginx-telego/templates/telego.locations" \
  "$rootfs/etc/nginx/snippets/telego.locations"

export NGINX_TELEGO_ROOT="$rootfs"

# The registry must be syntactically valid and classify pristine package files.
"$HELPER" validate
"$HELPER" status >"$work/status"
grep -Fq $'/etc/nginx/conf.d/telego.conf\tcore\tpackage\trequired\tok\t/usr/share/nginx-telego/templates/telego.conf' "$work/status"
grep -Fq $'/etc/nginx/snippets/telego.locations\tlocations\tpackage\trequired\tok\t/usr/share/nginx-telego/templates/telego.locations' "$work/status"
grep -Fq $'/etc/nginx/conf.d/zz-telego-managed.conf\tingress\tgenerated\tconditional\tabsent\trenderer' "$work/status"

# Manual drift in a package-owned active file must be visible, not adopted.
printf '\n# hand edited\n' >>"$rootfs/etc/nginx/conf.d/telego.conf"
"$HELPER" status >"$work/status"
grep -Fq $'/etc/nginx/conf.d/telego.conf\tcore\tpackage\trequired\tmodified\t' "$work/status"
cp "$rootfs/usr/share/nginx-telego/templates/telego.conf" \
  "$rootfs/etc/nginx/conf.d/telego.conf"

# Missing package-owned files and unsafe file types are distinct states.
rm -f "$rootfs/etc/nginx/snippets/telego.locations"
"$HELPER" status >"$work/status"
grep -Fq $'/etc/nginx/snippets/telego.locations\tlocations\tpackage\trequired\tmissing\t' "$work/status"
ln -s /tmp/not-a-real-snippet "$rootfs/etc/nginx/snippets/telego.locations"
"$HELPER" status >"$work/status"
grep -Fq $'/etc/nginx/snippets/telego.locations\tlocations\tpackage\trequired\tinvalid-type\t' "$work/status"
rm -f "$rootfs/etc/nginx/snippets/telego.locations"
cp "$rootfs/usr/share/nginx-telego/templates/telego.locations" \
  "$rootfs/etc/nginx/snippets/telego.locations"

# The generated path is owned only when it carries the renderer ownership marker.
printf '# user file\n' >"$rootfs/etc/nginx/conf.d/zz-telego-managed.conf"
"$HELPER" status >"$work/status"
grep -Fq $'/etc/nginx/conf.d/zz-telego-managed.conf\tingress\tgenerated\tconditional\tforeign\trenderer' "$work/status"

cat >"$rootfs/etc/nginx/conf.d/zz-telego-managed.conf" <<'EOF'
# Generated by /usr/libexec/nginx-telego-render from /etc/config/nginx_telego.
# test fixture
EOF
"$HELPER" status >"$work/status"
grep -Fq $'/etc/nginx/conf.d/zz-telego-managed.conf\tingress\tgenerated\tconditional\tmanaged\trenderer' "$work/status"

# Duplicate ownership declarations are rejected so two roles cannot claim one path.
cp "$rootfs/usr/share/nginx-telego/ownership.tsv" "$work/ownership-good.tsv"
grep '^/etc/nginx/conf.d/telego.conf' "$work/ownership-good.tsv" >>"$rootfs/usr/share/nginx-telego/ownership.tsv"
if "$HELPER" validate >"$work/duplicate.out" 2>&1; then
  echo 'duplicate managed path unexpectedly accepted' >&2
  exit 1
fi
grep -Fq 'duplicate managed path' "$work/duplicate.out"
cp "$work/ownership-good.tsv" "$rootfs/usr/share/nginx-telego/ownership.tsv"

# Canonical repair sources are package state; their loss is reported separately.
rm -f "$rootfs/usr/share/nginx-telego/templates/telego.conf"
"$HELPER" status >"$work/status"
grep -Fq $'/etc/nginx/conf.d/telego.conf\tcore\tpackage\trequired\tsource-missing\t' "$work/status"

echo 'nginx-telego ownership registry tests passed'
