#!/bin/bash
set -euo pipefail

ROOT=$(cd "$(dirname "$0")/../.." && pwd)
HELPER="$ROOT/package/nginx-telego/files/usr/libexec/nginx-telego-files"
work=$(mktemp -d)
trap 'rm -rf -- "$work"' EXIT

rootfs="$work/rootfs"
mkdir -p \
  "$rootfs/etc/nginx/conf.d" \
  "$rootfs/etc/nginx/snippets" \
  "$rootfs/usr/share/nginx-telego/templates"

cp "$ROOT/package/nginx-telego/files/conf.d/telego.conf" \
  "$rootfs/usr/share/nginx-telego/templates/telego.conf"
cp "$ROOT/package/nginx-telego/files/telego.locations" \
  "$rootfs/usr/share/nginx-telego/templates/telego.locations"
cp "$ROOT/package/nginx-telego/files/usr/share/nginx-telego/ownership.tsv" \
  "$rootfs/usr/share/nginx-telego/ownership.tsv"

cp "$rootfs/usr/share/nginx-telego/templates/telego.conf" \
  "$rootfs/etc/nginx/conf.d/telego.conf"
cp "$rootfs/usr/share/nginx-telego/templates/telego.locations" \
  "$rootfs/etc/nginx/snippets/telego.locations"

export NGINX_TELEGO_ROOT="$rootfs"
registry="$rootfs/usr/share/nginx-telego/ownership.tsv"
cp "$registry" "$work/ownership-good.tsv"

restore_registry() {
  cp "$work/ownership-good.tsv" "$registry"
}

expect_validate_fail() {
  local pattern=$1
  local output=$2
  if "$HELPER" validate >"$output" 2>&1; then
    echo "invalid ownership registry unexpectedly accepted: $pattern" >&2
    exit 1
  fi
  grep -Fq "$pattern" "$output"
  restore_registry
}

# The registry must be syntactically valid and classify pristine package files.
"$HELPER" validate
"$HELPER" status >"$work/status"
grep -Fq $'/etc/nginx/conf.d/telego.conf\tcore\tpackage\trequired\tok\t/usr/share/nginx-telego/templates/telego.conf' "$work/status"
grep -Fq $'/etc/nginx/snippets/telego.locations\tlocations\tpackage\trequired\tok\t/usr/share/nginx-telego/templates/telego.locations' "$work/status"
grep -Fq $'/etc/nginx/conf.d/zz-telego-managed.conf\tingress\tgenerated\tconditional\tabsent\trenderer' "$work/status"

# Manual drift in a package-owned active file must be visible, not adopted.
printf '\n# hand edited\n' >>"$rootfs/etc/nginx/conf.d/telego.conf"
"$HELPER" status >"$work/status"
grep -Fq $'/etc/nginx/conf.d/telego.conf\tcore\tpackage\trequired\tmodified\t' "$work/status"
cp "$rootfs/usr/share/nginx-telego/templates/telego.conf" \
  "$rootfs/etc/nginx/conf.d/telego.conf"

# Missing package-owned files and unsafe file types are distinct states.
rm -f "$rootfs/etc/nginx/snippets/telego.locations"
"$HELPER" status >"$work/status"
grep -Fq $'/etc/nginx/snippets/telego.locations\tlocations\tpackage\trequired\tmissing\t' "$work/status"
ln -s /tmp/not-a-real-snippet "$rootfs/etc/nginx/snippets/telego.locations"
"$HELPER" status >"$work/status"
grep -Fq $'/etc/nginx/snippets/telego.locations\tlocations\tpackage\trequired\tinvalid-type\t' "$work/status"
rm -f "$rootfs/etc/nginx/snippets/telego.locations"
cp "$rootfs/usr/share/nginx-telego/templates/telego.locations" \
  "$rootfs/etc/nginx/snippets/telego.locations"

# Canonical package repair sources distinguish absence from unsafe file types.
rm -f "$rootfs/usr/share/nginx-telego/templates/telego.conf"
"$HELPER" status >"$work/status"
grep -Fq $'/etc/nginx/conf.d/telego.conf\tcore\tpackage\trequired\tsource-missing\t' "$work/status"
ln -s /tmp/not-a-real-template "$rootfs/usr/share/nginx-telego/templates/telego.conf"
"$HELPER" status >"$work/status"
grep -Fq $'/etc/nginx/conf.d/telego.conf\tcore\tpackage\trequired\tsource-invalid-type\t' "$work/status"
rm -f "$rootfs/usr/share/nginx-telego/templates/telego.conf"
cp "$ROOT/package/nginx-telego/files/conf.d/telego.conf" \
  "$rootfs/usr/share/nginx-telego/templates/telego.conf"

# The generated path is owned only when it carries the renderer ownership marker.
printf '# user file\n' >"$rootfs/etc/nginx/conf.d/zz-telego-managed.conf"
"$HELPER" status >"$work/status"
grep -Fq $'/etc/nginx/conf.d/zz-telego-managed.conf\tingress\tgenerated\tconditional\tforeign\trenderer' "$work/status"

cat >"$rootfs/etc/nginx/conf.d/zz-telego-managed.conf" <<'EOF'
# Generated by /usr/libexec/nginx-telego-render from /etc/config/nginx_telego.
# test fixture
EOF
"$HELPER" status >"$work/status"
grep -Fq $'/etc/nginx/conf.d/zz-telego-managed.conf\tingress\tgenerated\tconditional\tmanaged\trenderer' "$work/status"

rm -f "$rootfs/etc/nginx/conf.d/zz-telego-managed.conf"
mkdir "$rootfs/etc/nginx/conf.d/zz-telego-managed.conf"
"$HELPER" status >"$work/status"
grep -Fq $'/etc/nginx/conf.d/zz-telego-managed.conf\tingress\tgenerated\tconditional\tinvalid-type\trenderer' "$work/status"
rmdir "$rootfs/etc/nginx/conf.d/zz-telego-managed.conf"
mkfifo "$rootfs/etc/nginx/conf.d/zz-telego-managed.conf"
"$HELPER" status >"$work/status"
grep -Fq $'/etc/nginx/conf.d/zz-telego-managed.conf\tingress\tgenerated\tconditional\tinvalid-type\trenderer' "$work/status"
rm -f "$rootfs/etc/nginx/conf.d/zz-telego-managed.conf"

# Duplicate declarations are rejected so two managed roles cannot claim one path.
grep '^/etc/nginx/conf.d/telego.conf' "$work/ownership-good.tsv" >>"$registry"
expect_validate_fail 'duplicate managed path' "$work/duplicate.out"

# The registry is a security boundary, not an arbitrary root filesystem manifest.
printf '/etc/passwd\tcore\tpackage\trequired\t/usr/share/nginx-telego/templates/telego.conf\n' >>"$registry"
expect_validate_fail 'managed conf.d path must be' "$work/outside-target.out"

printf '/etc/nginx/conf.d/extra.conf\tcore\tpackage\trequired\t/etc/passwd\n' >>"$registry"
expect_validate_fail 'package source must be under /usr/share/nginx-telego/templates/' "$work/outside-source.out"

printf '/etc/nginx/conf.d/extra.conf\tunknown\tpackage\trequired\t/usr/share/nginx-telego/templates/telego.conf\n' >>"$registry"
expect_validate_fail "invalid role 'unknown'" "$work/role.out"

printf '/etc/nginx/conf.d/extra.conf\tcore\tpackage\trequired\t\n' >>"$registry"
expect_validate_fail 'missing source' "$work/source-empty.out"

printf '/etc/nginx/conf.d/../escape.conf\tcore\tpackage\trequired\t/usr/share/nginx-telego/templates/telego.conf\n' >>"$registry"
expect_validate_fail 'managed path contains dot traversal' "$work/traversal.out"

"$HELPER" validate

echo 'nginx-telego ownership registry tests passed'
