#!/bin/bash
set -euo pipefail

ROOT=$(cd "$(dirname "$0")/../.." && pwd)
RECONCILE="$ROOT/package/nginx-telego/files/usr/libexec/nginx-telego-reconcile"
FILES="$ROOT/package/nginx-telego/files/usr/libexec/nginx-telego-files"
RENDER="$ROOT/package/nginx-telego/files/usr/libexec/nginx-telego-render"
work=$(mktemp -d)
trap 'rm -rf -- "$work"' EXIT

rootfs="$work/rootfs"
mkdir -p \
  "$rootfs/etc/nginx/conf.d" \
  "$rootfs/etc/nginx/snippets" \
  "$rootfs/etc/config" \
  "$rootfs/usr/share/nginx-telego/templates" \
  "$rootfs/var/lock"

cp "$ROOT/package/nginx-telego/files/conf.d/telego.conf" \
  "$rootfs/usr/share/nginx-telego/templates/telego.conf"
cp "$ROOT/package/nginx-telego/files/telego.locations" \
  "$rootfs/usr/share/nginx-telego/templates/telego.locations"
cp "$ROOT/package/nginx-telego/files/usr/share/nginx-telego/ownership.tsv" \
  "$rootfs/usr/share/nginx-telego/ownership.tsv"
cp "$rootfs/usr/share/nginx-telego/templates/telego.conf" \
  "$rootfs/etc/nginx/conf.d/telego.conf"
cp "$rootfs/usr/share/nginx-telego/templates/telego.locations" \
  "$rootfs/etc/nginx/snippets/telego.locations"

cat >"$work/uci" <<'SH'
#!/bin/sh
[ "$1" = '-q' ] && shift
[ "$1" = 'get' ] || exit 1
case "$2" in
  nginx_telego.shared.enabled) printf '%s\n' "${FIX_SHARED_ENABLED:-0}" ;;
  nginx_telego.shared.hostname) printf '%s\n' "${FIX_SHARED_HOSTNAME:-}" ;;
  nginx_telego.shared.certificate) printf '%s\n' "${FIX_CERT:-}" ;;
  nginx_telego.shared.certificate_key) printf '%s\n' "${FIX_KEY:-}" ;;
  nginx_telego.cloudflare.enabled) printf '%s\n' "${FIX_CF_ENABLED:-0}" ;;
  nginx_telego.cloudflare.hostname) printf '%s\n' "${FIX_CF_HOSTNAME:-}" ;;
  nginx_telego.fallback.manage) printf '%s\n' "${FIX_FALLBACK_MANAGE:-1}" ;;
  telego.general.bind_to) printf '%s\n' "${FIX_PUBLIC_BIND:-0.0.0.0:443}" ;;
  telego.web_proxy.enabled) printf '%s\n' "${FIX_WEB_ENABLED:-1}" ;;
  telego.web_proxy.hostname) printf '%s\n' "${FIX_WEB_HOSTNAME:-web.example.com}" ;;
  telego.web_proxy.bind_to) printf '%s\n' "${FIX_WEB_BIND:-127.0.0.1:8080}" ;;
  telego.web_proxy.trusted_proxy_cidrs) printf '%s\n' "${FIX_TRUSTED:-127.0.0.1/32}" ;;
  telego.tls_fronting.mask_host) printf '%s\n' "${FIX_MASK_HOST:-proxy.example.com}" ;;
  telego.tls_fronting.cert_host) printf '%s\n' "${FIX_CERT_HOST:-127.0.0.1}" ;;
  telego.tls_fronting.cert_port) printf '%s\n' "${FIX_CERT_PORT:-8444}" ;;
  telego.tls_fronting.splice_host) printf '%s\n' "${FIX_SPLICE_HOST:-127.0.0.1}" ;;
  telego.tls_fronting.splice_port) printf '%s\n' "${FIX_SPLICE_PORT:-8443}" ;;
  telego.tls_fronting.splice_proxy_protocol) printf '%s\n' "${FIX_SPLICE_PROXY:-2}" ;;
  *) exit 1 ;;
esac
SH
chmod +x "$work/uci"

cat >"$work/nginx" <<'SH'
#!/bin/sh
printf '%s\n' "$*" >>"$NGINX_LOG"
[ "${NGINX_TEST_FAIL:-0}" != 1 ]
SH
chmod +x "$work/nginx"

cat >"$work/nginx-init" <<'SH'
#!/bin/sh
case "$1" in
  status) exit 0 ;;
  reload) printf 'reload\n' >>"$NGINX_RELOAD_LOG" ;;
  *) exit 0 ;;
esac
SH
chmod +x "$work/nginx-init"

: >"$rootfs/etc/nginx/uci.conf"
: >"$rootfs/etc/config/nginx"
printf 'dummy cert\n' >"$work/fullchain.pem"
printf 'dummy key\n' >"$work/privkey.pem"

export NGINX_TELEGO_ROOT="$rootfs"
export NGINX_TELEGO_FILES="$FILES"
export NGINX_TELEGO_RENDER="$RENDER"
export NGINX_TELEGO_MANIFEST="$rootfs/usr/share/nginx-telego/ownership.tsv"
export NGINX_TELEGO_CONF_DIR="$rootfs/etc/nginx/conf.d"
export NGINX_TELEGO_INGRESS_OUTPUT="$rootfs/etc/nginx/conf.d/80-telego-ingress.conf"
export NGINX_TELEGO_FALLBACK_OUTPUT="$rootfs/etc/nginx/conf.d/85-telego-fallback.conf"
export NGINX_TELEGO_LEGACY_OUTPUT_PATH="/etc/nginx/conf.d/zz-telego-managed.conf"
export NGINX_TELEGO_LOCK_DIR="$work/reconcile.lock"
export UCI_BIN="$work/uci"
export NGINX_BIN="$work/nginx"
export NGINX_CONF="$rootfs/etc/nginx/uci.conf"
export NGINX_INIT="$work/nginx-init"
export NGINX_UCI_CONFIG="$rootfs/etc/config/nginx"
export NGINX_LOG="$work/nginx.log"
export NGINX_RELOAD_LOG="$work/reload.log"
export FIX_CERT="$work/fullchain.pem" FIX_KEY="$work/privkey.pem"
: >"$NGINX_LOG"
: >"$NGINX_RELOAD_LOG"

INGRESS="$NGINX_TELEGO_INGRESS_OUTPUT"
FALLBACK="$NGINX_TELEGO_FALLBACK_OUTPUT"
LEGACY="$rootfs$NGINX_TELEGO_LEGACY_OUTPUT_PATH"
MARKER='# Generated by /usr/libexec/nginx-telego-render from /etc/config/nginx_telego.'

# A pristine disabled installation validates but creates no generated files.
export FIX_SHARED_ENABLED=0 FIX_CF_ENABLED=0
"$RECONCILE" apply
! test -e "$INGRESS"
! test -e "$FALLBACK"
[[ ! -s "$NGINX_RELOAD_LOG" ]]

# Safe package drift is repaired from canonical copies.
printf '\n# hand edited\n' >>"$rootfs/etc/nginx/conf.d/telego.conf"
rm -f "$rootfs/etc/nginx/snippets/telego.locations"
"$RECONCILE" apply
cmp "$rootfs/usr/share/nginx-telego/templates/telego.conf" \
  "$rootfs/etc/nginx/conf.d/telego.conf"
cmp "$rootfs/usr/share/nginx-telego/templates/telego.locations" \
  "$rootfs/etc/nginx/snippets/telego.locations"
[[ $(wc -l <"$NGINX_RELOAD_LOG") == 1 ]]

# Enabling Cloudflare creates separate ingress and fallback files; repeat is no-op.
export FIX_CF_ENABLED=1 FIX_CF_HOSTNAME=web.example.com FIX_WEB_HOSTNAME=web.example.com
"$RECONCILE" apply
grep -Fq "$MARKER" "$INGRESS"
grep -Fq "$MARKER" "$FALLBACK"
grep -q 'listen 127.0.0.1:18080;' "$INGRESS"
grep -q 'listen 127.0.0.1:8090;' "$FALLBACK"
[[ $(wc -l <"$NGINX_RELOAD_LOG") == 2 ]]
reloads=$(wc -l <"$NGINX_RELOAD_LOG")
"$RECONCILE" apply
[[ $(wc -l <"$NGINX_RELOAD_LOG") == "$reloads" ]]

# A final validation failure restores package drift and both generated files.
printf '\n# pre-transaction drift\n' >>"$rootfs/etc/nginx/conf.d/telego.conf"
cp "$rootfs/etc/nginx/conf.d/telego.conf" "$work/core-before-fail"
cp "$INGRESS" "$work/ingress-before-fail"
cp "$FALLBACK" "$work/fallback-before-fail"
export FIX_CF_ENABLED=0 NGINX_TEST_FAIL=1
if "$RECONCILE" apply >"$work/reconcile-fail.out" 2>&1; then
  echo 'reconciliation unexpectedly succeeded while nginx -t was forced to fail' >&2
  exit 1
fi
cmp "$work/core-before-fail" "$rootfs/etc/nginx/conf.d/telego.conf"
cmp "$work/ingress-before-fail" "$INGRESS"
cmp "$work/fallback-before-fail" "$FALLBACK"
[[ $(wc -l <"$NGINX_RELOAD_LOG") == "$reloads" ]]
grep -Eq 'renderer rejected the desired state|final nginx -t failed' "$work/reconcile-fail.out"
unset NGINX_TEST_FAIL

# Next valid disabled apply repairs package drift and removes current generated files.
"$RECONCILE" apply
cmp "$rootfs/usr/share/nginx-telego/templates/telego.conf" \
  "$rootfs/etc/nginx/conf.d/telego.conf"
! test -e "$INGRESS"
! test -e "$FALLBACK"
[[ $(wc -l <"$NGINX_RELOAD_LOG") == $((reloads + 1)) ]]
reloads=$(wc -l <"$NGINX_RELOAD_LOG")

# A marker-owned legacy combined file migrates to the split desired state.
printf '%s\nserver { listen 127.0.0.1:18080; }\n' "$MARKER" >"$LEGACY"
export FIX_CF_ENABLED=1
"$RECONCILE" apply
! test -e "$LEGACY"
test -f "$INGRESS"
test -f "$FALLBACK"
grep -q 'listen 127.0.0.1:18080;' "$INGRESS"
grep -q 'listen 127.0.0.1:8090;' "$FALLBACK"
[[ $(wc -l <"$NGINX_RELOAD_LOG") == $((reloads + 1)) ]]
reloads=$(wc -l <"$NGINX_RELOAD_LOG")

# Failed migration restores the old combined file and removes staged split state.
export FIX_CF_ENABLED=0
"$RECONCILE" apply
! test -e "$INGRESS"
! test -e "$FALLBACK"
reloads=$(wc -l <"$NGINX_RELOAD_LOG")
printf '%s\nserver { listen 127.0.0.1:18080; }\n' "$MARKER" >"$LEGACY"
cp "$LEGACY" "$work/legacy-before-fail"
export FIX_CF_ENABLED=1 NGINX_TEST_FAIL=1
if "$RECONCILE" apply >"$work/legacy-fail.out" 2>&1; then
  echo 'legacy migration unexpectedly succeeded while nginx -t was forced to fail' >&2
  exit 1
fi
cmp "$work/legacy-before-fail" "$LEGACY"
! test -e "$INGRESS"
! test -e "$FALLBACK"
grep -q 'transaction rolled back' "$work/legacy-fail.out"
unset NGINX_TEST_FAIL
rm -f "$LEGACY"
export FIX_CF_ENABLED=0

# Foreign legacy file is outside package ownership and remains untouched.
printf '# administrator-owned legacy filename\n' >"$LEGACY"
cp "$LEGACY" "$work/legacy-foreign"
"$RECONCILE" apply
cmp "$work/legacy-foreign" "$LEGACY"
[[ $(wc -l <"$NGINX_RELOAD_LOG") == "$reloads" ]]
rm -f "$LEGACY"

# A foreign current ingress file is preserved disabled and blocks enablement.
printf '# administrator-owned reserved file\n' >"$INGRESS"
cp "$INGRESS" "$work/foreign-before"
"$RECONCILE" apply
cmp "$work/foreign-before" "$INGRESS"
[[ $(wc -l <"$NGINX_RELOAD_LOG") == "$reloads" ]]

export FIX_CF_ENABLED=1
if "$RECONCILE" apply >"$work/foreign-enable.out" 2>&1; then
  echo 'managed profile unexpectedly replaced a foreign current ingress file' >&2
  exit 1
fi
cmp "$work/foreign-before" "$INGRESS"
[[ $(wc -l <"$NGINX_RELOAD_LOG") == "$reloads" ]]
export FIX_CF_ENABLED=0
rm -f "$INGRESS"

# Unsafe current and legacy types are rejected before renderer mutation.
rm -f "$rootfs/etc/nginx/snippets/telego.locations"
ln -s /tmp/not-a-real-snippet "$rootfs/etc/nginx/snippets/telego.locations"
if "$RECONCILE" apply >"$work/unsafe.out" 2>&1; then
  echo 'reconciliation unexpectedly accepted a symlink package-owned file' >&2
  exit 1
fi
grep -q 'unsafe active file type' "$work/unsafe.out"
test -L "$rootfs/etc/nginx/snippets/telego.locations"
rm -f "$rootfs/etc/nginx/snippets/telego.locations"
cp "$rootfs/usr/share/nginx-telego/templates/telego.locations" \
  "$rootfs/etc/nginx/snippets/telego.locations"

ln -s /tmp/not-a-real-legacy "$LEGACY"
if "$RECONCILE" apply >"$work/legacy-unsafe.out" 2>&1; then
  echo 'reconciliation unexpectedly accepted a legacy symlink' >&2
  exit 1
fi
grep -q 'unsafe legacy generated-path type' "$work/legacy-unsafe.out"
rm -f "$LEGACY"

# Concurrent reconciliation is rejected by the process lock.
mkdir "$NGINX_TELEGO_LOCK_DIR"
printf '%s\n' "$$" >"$NGINX_TELEGO_LOCK_DIR/pid"
if "$RECONCILE" apply >"$work/lock.out" 2>&1; then
  echo 'reconciliation unexpectedly ignored an active lock' >&2
  exit 1
fi
grep -q 'another reconciliation is already running' "$work/lock.out"
rm -rf "$NGINX_TELEGO_LOCK_DIR"

echo 'nginx-telego reconciliation transaction tests passed'
