#!/bin/bash
set -euo pipefail

ROOT=$(cd "$(dirname "$0")/../.." && pwd)
RECONCILE="$ROOT/package/nginx-telego/files/usr/libexec/nginx-telego-reconcile"
FILES="$ROOT/package/nginx-telego/files/usr/libexec/nginx-telego-files"
RENDER="$ROOT/package/nginx-telego/files/usr/libexec/nginx-telego-render"
work=$(mktemp -d)
trap 'rm -rf -- "$work"' EXIT

rootfs="$work/rootfs"
mkdir -p \
  "$rootfs/etc/nginx/conf.d" \
  "$rootfs/etc/nginx/snippets" \
  "$rootfs/etc/config" \
  "$rootfs/usr/share/nginx-telego/templates" \
  "$rootfs/var/lock"

cp "$ROOT/package/nginx-telego/files/conf.d/20-telego-core.conf" \
  "$rootfs/usr/share/nginx-telego/templates/20-telego-core.conf"
cp "$ROOT/package/nginx-telego/files/telego.locations" \
  "$rootfs/usr/share/nginx-telego/templates/telego.locations"
cp "$ROOT/package/nginx-telego/files/usr/share/nginx-telego/ownership.tsv" \
  "$rootfs/usr/share/nginx-telego/ownership.tsv"
cp "$rootfs/usr/share/nginx-telego/templates/20-telego-core.conf" \
  "$rootfs/etc/nginx/conf.d/20-telego-core.conf"
cp "$rootfs/usr/share/nginx-telego/templates/telego.locations" \
  "$rootfs/etc/nginx/snippets/telego.locations"

cat >"$work/uci" <<'SH'
#!/bin/sh
[ "$1" = '-q' ] && shift
[ "$1" = 'get' ] || exit 1
case "$2" in
  nginx_telego.shared.enabled) printf '%s\n' "${FIX_SHARED_ENABLED:-0}" ;;
  nginx_telego.shared.hostname) printf '%s\n' "${FIX_SHARED_HOSTNAME:-}" ;;
  nginx_telego.shared.certificate) printf '%s\n' "${FIX_CERT:-}" ;;
  nginx_telego.shared.certificate_key) printf '%s\n' "${FIX_KEY:-}" ;;
  nginx_telego.cloudflare.enabled) printf '%s\n' "${FIX_CF_ENABLED:-0}" ;;
  nginx_telego.cloudflare.hostname) printf '%s\n' "${FIX_CF_HOSTNAME:-}" ;;
  nginx_telego.fallback.manage) printf '%s\n' "${FIX_FALLBACK_MANAGE:-1}" ;;
  telego.general.bind_to) printf '%s\n' "${FIX_PUBLIC_BIND:-0.0.0.0:443}" ;;
  telego.web_proxy.enabled) printf '%s\n' "${FIX_WEB_ENABLED:-1}" ;;
  telego.web_proxy.hostname) printf '%s\n' "${FIX_WEB_HOSTNAME:-web.example.com}" ;;
  telego.web_proxy.bind_to) printf '%s\n' "${FIX_WEB_BIND:-127.0.0.1:8080}" ;;
  telego.web_proxy.trusted_proxy_cidrs) printf '%s\n' "${FIX_TRUSTED:-127.0.0.1/32}" ;;
  telego.tls_fronting.mask_host) printf '%s\n' "${FIX_MASK_HOST:-proxy.example.com}" ;;
  telego.tls_fronting.cert_host) printf '%s\n' "${FIX_CERT_HOST:-127.0.0.1}" ;;
  telego.tls_fronting.cert_port) printf '%s\n' "${FIX_CERT_PORT:-8444}" ;;
  telego.tls_fronting.splice_host) printf '%s\n' "${FIX_SPLICE_HOST:-127.0.0.1}" ;;
  telego.tls_fronting.splice_port) printf '%s\n' "${FIX_SPLICE_PORT:-8443}" ;;
  telego.tls_fronting.splice_proxy_protocol) printf '%s\n' "${FIX_SPLICE_PROXY:-2}" ;;
  *) exit 1 ;;
esac
SH
chmod +x "$work/uci"

cat >"$work/nginx" <<'SH'
#!/bin/sh
printf '%s\n' "$*" >>"$NGINX_LOG"
[ "${NGINX_TEST_FAIL:-0}" != 1 ]
SH
chmod +x "$work/nginx"

cat >"$work/nginx-init" <<'SH'
#!/bin/sh
case "$1" in
  status) exit 0 ;;
  reload)
    printf 'reload\n' >>"$NGINX_RELOAD_LOG"
    [ "${NGINX_RELOAD_FAIL:-0}" != 1 ]
    ;;
  *) exit 0 ;;
esac
SH
chmod +x "$work/nginx-init"

: >"$rootfs/etc/nginx/uci.conf"
: >"$rootfs/etc/config/nginx"
printf 'dummy cert\n' >"$work/fullchain.pem"
printf 'dummy key\n' >"$work/privkey.pem"

export NGINX_TELEGO_ROOT="$rootfs"
export NGINX_TELEGO_FILES="$FILES"
export NGINX_TELEGO_RENDER="$RENDER"
export NGINX_TELEGO_MANIFEST="$rootfs/usr/share/nginx-telego/ownership.tsv"
export NGINX_TELEGO_CONF_DIR="$rootfs/etc/nginx/conf.d"
export NGINX_TELEGO_INGRESS_OUTPUT="$rootfs/etc/nginx/conf.d/80-telego-ingress.conf"
export NGINX_TELEGO_FALLBACK_OUTPUT="$rootfs/etc/nginx/conf.d/85-telego-fallback.conf"
export NGINX_TELEGO_LOCK_DIR="$work/reconcile.lock"
export UCI_BIN="$work/uci"
export NGINX_BIN="$work/nginx"
export NGINX_CONF="$rootfs/etc/nginx/uci.conf"
export NGINX_INIT="$work/nginx-init"
export NGINX_UCI_CONFIG="$rootfs/etc/config/nginx"
export NGINX_LOG="$work/nginx.log"
export NGINX_RELOAD_LOG="$work/reload.log"
export FIX_CERT="$work/fullchain.pem" FIX_KEY="$work/privkey.pem"
: >"$NGINX_LOG"
: >"$NGINX_RELOAD_LOG"

CORE="$rootfs/etc/nginx/conf.d/20-telego-core.conf"
SNIPPET="$rootfs/etc/nginx/snippets/telego.locations"
INGRESS="$NGINX_TELEGO_INGRESS_OUTPUT"
FALLBACK="$NGINX_TELEGO_FALLBACK_OUTPUT"
MARKER='# Generated by /usr/libexec/nginx-telego-render from /etc/config/nginx_telego.'
INGRESS_ROLE='# nginx-telego-role: ingress'
FALLBACK_ROLE='# nginx-telego-role: fallback'
OLD_INGRESS_ROLE='# Role: ingress. Do not edit this file directly.'

# Pristine disabled baseline is a no-op.
export FIX_SHARED_ENABLED=0 FIX_CF_ENABLED=0 FIX_FALLBACK_MANAGE=1
"$RECONCILE" apply
! test -e "$INGRESS"
! test -e "$FALLBACK"
[[ ! -s "$NGINX_RELOAD_LOG" ]]

# Safe package drift is restored from canonical package sources.
printf '\n# hand edited\n' >>"$CORE"
rm -f "$SNIPPET"
"$RECONCILE" apply
cmp "$rootfs/usr/share/nginx-telego/templates/20-telego-core.conf" "$CORE"
cmp "$rootfs/usr/share/nginx-telego/templates/telego.locations" "$SNIPPET"
[[ $(wc -l <"$NGINX_RELOAD_LOG") == 1 ]]
reloads=$(wc -l <"$NGINX_RELOAD_LOG")

# Cloudflare creates current role-marked ingress/fallback files; repeat is no-op.
export FIX_CF_ENABLED=1 FIX_CF_HOSTNAME=web.example.com FIX_WEB_HOSTNAME=web.example.com
"$RECONCILE" apply
grep -Fqx "$MARKER" "$INGRESS"
grep -Fqx "$INGRESS_ROLE" "$INGRESS"
grep -Fqx "$FALLBACK_ROLE" "$FALLBACK"
grep -q 'listen 127.0.0.1:18080;' "$INGRESS"
grep -q 'listen 127.0.0.1:8090;' "$FALLBACK"
[[ $(wc -l <"$NGINX_RELOAD_LOG") == $((reloads + 1)) ]]
reloads=$(wc -l <"$NGINX_RELOAD_LOG")
"$RECONCILE" apply
[[ $(wc -l <"$NGINX_RELOAD_LOG") == "$reloads" ]]

# fallback.manage 1 -> 0 removes only the managed fallback and keeps ingress.
export FIX_FALLBACK_MANAGE=0
"$RECONCILE" apply
test -f "$INGRESS"
! test -e "$FALLBACK"
[[ $(wc -l <"$NGINX_RELOAD_LOG") == $((reloads + 1)) ]]
reloads=$(wc -l <"$NGINX_RELOAD_LOG")
export FIX_FALLBACK_MANAGE=1
"$RECONCILE" apply
test -f "$FALLBACK"
reloads=$(wc -l <"$NGINX_RELOAD_LOG")

# Final validation failure restores package drift and generated state.
printf '\n# pre-transaction drift\n' >>"$CORE"
cp "$CORE" "$work/core-before-test-fail"
cp "$INGRESS" "$work/ingress-before-test-fail"
cp "$FALLBACK" "$work/fallback-before-test-fail"
export FIX_CF_ENABLED=0 NGINX_TEST_FAIL=1
if "$RECONCILE" apply >"$work/test-fail.out" 2>&1; then
  echo 'reconciliation unexpectedly succeeded while nginx -t was forced to fail' >&2
  exit 1
fi
cmp "$work/core-before-test-fail" "$CORE"
cmp "$work/ingress-before-test-fail" "$INGRESS"
cmp "$work/fallback-before-test-fail" "$FALLBACK"
[[ $(wc -l <"$NGINX_RELOAD_LOG") == "$reloads" ]]
grep -Eq 'renderer rejected the desired state|final nginx -t failed' "$work/test-fail.out"
unset NGINX_TEST_FAIL

# Reload failure also rolls the complete filesystem transaction back.
cp "$CORE" "$work/core-before-reload-fail"
cp "$INGRESS" "$work/ingress-before-reload-fail"
cp "$FALLBACK" "$work/fallback-before-reload-fail"
export NGINX_RELOAD_FAIL=1 FIX_CF_ENABLED=0
if "$RECONCILE" apply >"$work/reload-fail.out" 2>&1; then
  echo 'reconciliation unexpectedly succeeded while reload was forced to fail' >&2
  exit 1
fi
cmp "$work/core-before-reload-fail" "$CORE"
cmp "$work/ingress-before-reload-fail" "$INGRESS"
cmp "$work/fallback-before-reload-fail" "$FALLBACK"
grep -q 'nginx reload failed' "$work/reload-fail.out"
unset NGINX_RELOAD_FAIL
reloads=$(wc -l <"$NGINX_RELOAD_LOG")

# Next valid disabled apply repairs package drift and removes current generated state.
"$RECONCILE" apply
cmp "$rootfs/usr/share/nginx-telego/templates/20-telego-core.conf" "$CORE"
! test -e "$INGRESS"
! test -e "$FALLBACK"
[[ $(wc -l <"$NGINX_RELOAD_LOG") == $((reloads + 1)) ]]
reloads=$(wc -l <"$NGINX_RELOAD_LOG")

# A foreign file on a current reserved path is preserved while disabled and blocks enablement.
printf '# administrator-owned fallback filename\n' >"$FALLBACK"
cp "$FALLBACK" "$work/fallback-foreign"
"$RECONCILE" apply
cmp "$work/fallback-foreign" "$FALLBACK"
export FIX_CF_ENABLED=1 FIX_FALLBACK_MANAGE=1
if "$RECONCILE" apply >"$work/fallback-enable.out" 2>&1; then
  echo 'managed profile unexpectedly replaced a foreign fallback file' >&2
  exit 1
fi
cmp "$work/fallback-foreign" "$FALLBACK"
rm -f "$FALLBACK"
export FIX_CF_ENABLED=0

# Cross-role and pre-baseline role markers are foreign and block ingress enablement.
printf '%s\n%s\n' "$MARKER" "$FALLBACK_ROLE" >"$INGRESS"
cp "$INGRESS" "$work/cross-role"
export FIX_CF_ENABLED=1
if "$RECONCILE" apply >"$work/cross-role.out" 2>&1; then
  echo 'cross-role generated file was unexpectedly adopted' >&2
  exit 1
fi
cmp "$work/cross-role" "$INGRESS"
rm -f "$INGRESS"
printf '%s\n%s\n' "$MARKER" "$OLD_INGRESS_ROLE" >"$INGRESS"
cp "$INGRESS" "$work/old-role"
if "$RECONCILE" apply >"$work/old-role.out" 2>&1; then
  echo 'pre-baseline generated file was unexpectedly adopted' >&2
  exit 1
fi
cmp "$work/old-role" "$INGRESS"
rm -f "$INGRESS"
export FIX_CF_ENABLED=0

# Unsafe managed path types are rejected before renderer mutation.
rm -f "$SNIPPET"
ln -s /tmp/not-a-real-snippet "$SNIPPET"
if "$RECONCILE" apply >"$work/unsafe-package.out" 2>&1; then
  echo 'reconciliation unexpectedly accepted a symlink package-owned file' >&2
  exit 1
fi
grep -q 'unsafe active file type' "$work/unsafe-package.out"
rm -f "$SNIPPET"
cp "$rootfs/usr/share/nginx-telego/templates/telego.locations" "$SNIPPET"
ln -s /tmp/not-a-real-ingress "$INGRESS"
if "$RECONCILE" apply >"$work/unsafe-generated.out" 2>&1; then
  echo 'reconciliation unexpectedly accepted a symlink generated path' >&2
  exit 1
fi
grep -q 'unsafe generated-path type' "$work/unsafe-generated.out"
rm -f "$INGRESS"

# A stale lock is recovered automatically.
mkdir -p "$NGINX_TELEGO_LOCK_DIR"
printf '99999999\n' >"$NGINX_TELEGO_LOCK_DIR/pid"
"$RECONCILE" apply
! test -e "$NGINX_TELEGO_LOCK_DIR"

# An active lock refuses a concurrent writer.
mkdir -p "$NGINX_TELEGO_LOCK_DIR"
printf '%s\n' "$$" >"$NGINX_TELEGO_LOCK_DIR/pid"
if "$RECONCILE" apply >"$work/active-lock.out" 2>&1; then
  echo 'reconciliation unexpectedly ignored an active lock' >&2
  exit 1
fi
grep -q 'another reconciliation is already running' "$work/active-lock.out"
rm -rf "$NGINX_TELEGO_LOCK_DIR"

# remove-generated removes only currently owned generated paths and leaves foreign state.
export FIX_CF_ENABLED=1 FIX_FALLBACK_MANAGE=1
"$RECONCILE" apply
test -f "$INGRESS"
test -f "$FALLBACK"
printf '# administrator-owned fallback after apply\n' >"$FALLBACK"
cp "$FALLBACK" "$work/remove-foreign-fallback"
"$RECONCILE" remove-generated --no-reload
! test -e "$INGRESS"
cmp "$work/remove-foreign-fallback" "$FALLBACK"
test -f "$CORE"
test -f "$SNIPPET"

"$FILES" validate
"$FILES" status >"$work/final-status"
grep -Fq $'/etc/nginx/conf.d/20-telego-core.conf\tcore\tpackage\trequired\tok\t' "$work/final-status"
grep -Fq $'/etc/nginx/conf.d/80-telego-ingress.conf\tingress\tgenerated\tconditional\tabsent\t' "$work/final-status"
grep -Fq $'/etc/nginx/conf.d/85-telego-fallback.conf\tfallback\tgenerated\tconditional\tforeign\t' "$work/final-status"

echo 'nginx-telego reconciliation tests passed'
