name: Build telEgo Packages

on:
  push:
    branches: [main]
    paths:
      - 'package/**'
      - '.github/workflows/build-telego.yaml'
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  TELEGO_VERSION: "0.6.0"

jobs:
  build-all-packages:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.27'
          cache-dependency-path: telego-src/go.sum
      
      - name: Build Go Binary
        run: |
          cd telego-src
          go build -buildmode=pie -ldflags="-s -w" -o telego ./cmd/telego
          mkdir -p ../telego-pkg/files/usr/bin/
          cp telego ../telego-pkg/files/usr/bin/telego
          chmod +x ../telego-pkg/files/usr/bin/telego
      
      - name: Build OpenWrt APK Packages
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: "x86_64"
          FEED_DIR: "${{ github.workspace }}"
          PACKAGES: "telego-pkg nginx-telego luci-app-telego"
          IGNORE_ERRORS: 1
          INDEX: 1
          V: "s"
      
      - name: Store packages
        uses: actions/upload-artifact@v4
        with:
          name: telEgo-openwrt-apk-packages
          path: bin/packages/**/*.apk